#!/bin/sh
SERVICE_NAME="Red Led"
export LD_LIBRARY_PATH='/mnt/lib/:/lib/:/usr/lib/'

. /mnt/scripts/common_functions.sh

status()
{
  state=$(red_led status)
  if [[ $state == "ON" || $state == "on" ]]; then
    echo "PID: OK" 
  fi
}

start()
{
  blue_led off
  red_led on
}

stop()
{
  red_led off
}

if [ $# -eq 0 ]; then
  start
else
  case $1 in start|stop|status)
    $1
    ;;
  esac
fi

