#!/bin/sh
SERVICE_NAME="RTSP H264/H265 Server"
PIDFILE="/var/run/v4l2rtspserver.pid"
WATCHDOG_PIDFILE="/var/run/v4l2rtspserver-watch.pid"
LOGDIR="/mnt/log"
LOGPATH="$LOGDIR/v4l2rtspserver.log"
CONFIGPATH="/mnt/config"
export LD_LIBRARY_PATH='/mnt/lib/:/thirdlib:/system/lib/:/usr/lib/'

. /mnt/scripts/common_functions.sh
. /mnt/scripts/update_timezone.sh

install_config $CONFIGPATH/rtspserver.conf

status()
{
  pid="$(cat "$PIDFILE" 2>/dev/null)"
  if [ "$pid" ]; then
    # Prints PID: $pid if exists and returns 0(no error) else returns 1(error condition)
    kill -0 "$pid" >/dev/null && echo "PID: $pid" || return 1
  fi
}

start()
{
  if [ "$(status)" != "" ]; then
    echo "A v4l2rtspserver is already running, please stop it or reboot"
  else
    echo "Starting v4l2rtspserver"

    IFS=" "
    set -- $(/mnt/bin/rwconf $CONFIGPATH/rtspserver.conf r \
      " "  PORT             \
      " "  RTSPLOGENABLED   \
      2    codec            \
      3    codec)

    PORT=$1          
    RTSPLOGENABLED=$2 
    audioCodec0=$3
    audioCodec1=$4
    USERNAME=$(read_config rtspserver.conf USERNAME)
    USERPASSWORD=$(read_config rtspserver.conf USERPASSWORD)

    ## UserName and password
    if [ "$USERNAME" != "" ]; then
        CREDENTIAL="-U $USERNAME:$USERPASSWORD"
    fi

    ## Port
    if [ "$PORT" != "" ]; then
        PORT="-P $PORT"
    fi
   
    ## Log
    if [ $RTSPLOGENABLED -eq 0 ]; then
        LOGPATH="/dev/null"
    fi

    ## Audio
    AUDIO0=",audio0"
    AUDIO1=",audio1"
    if [ $audioCodec0 -eq 0 ]; then
        AUDIO0=""
    fi
    if [ $audioCodec1 -eq 0 ]; then
        AUDIO1=""
    fi

    restart_service_if_need /mnt/controlscripts/onvif

    echo "================== START ===============" >> "$LOGPATH"
    echo "/mnt/bin/v4l2rtspserver  video0$AUDIO0 video1$AUDIO1 $CREDENTIAL $PORT" >> "$LOGPATH"
    /mnt/bin/v4l2rtspserver -c -Q 20 video0$AUDIO0 video1$AUDIO1 $CREDENTIAL $PORT 2>> "$LOGPATH" >> "$LOGPATH" &
    echo "$!" > "$PIDFILE"

    ## Watchdog
    if ! checkpid "$WATCHDOG_PIDFILE"; then
      /mnt/scripts/service-watchdog.sh /mnt/controlscripts/rtsp-h26x 1 &
      echo "$!" > "$WATCHDOG_PIDFILE"
    fi
  fi
}

stop()
{
  killpid "$WATCHDOG_PIDFILE"
  killpid "$PIDFILE"
}

if [ $# -eq 0 ]; then
  start
else
  case $1 in start|stop|status)
    $1
    ;;
  esac
fi
